on:
  push:
    branches:
      - main

permissions:
  contents: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: php
          token: ${{ secrets.GITHUB_TOKEN }}
